import database
import streamlit as st
import pandas as pd
from datetime import datetime, date
import json
import os
import io
import base64
import urllib.parse
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter, landscape
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from printer_service import calculate_printer_difference, get_printers
from database import save_db
from database import load_db
db = load_db()
st.write(db)


def sync_draft():
    if st.session_state.get("logged_in"):
        user = st.session_state.get("user")
        if not user:
            return

        draft_keys = (
            's_','o_','e_','c_','m_','i_',
            'ks','xs','op','u10','v22','ex',
            'kj','xj','dn','k1','k2','x1','x2'
        )

        draft_data = {
            k: v
            for k, v in st.session_state.items()
            if k.startswith(draft_keys)
        }

        if "drafts" not in db:
            db["drafts"] = {}

        db["drafts"][user] = draft_data
        save_db(db)
if "users" not in db:
    db["users"] = {}
    save_db(db)



# --- 2. Advanced PDF Generation (تقرير شامل) ---
def create_downloadable_pdf(branch, staff_name, date_str, sales, expenses, exp_note, diff, kyo_data, xerox_data, opay_move, debit_v22):
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=landscape(letter), topMargin=30, bottomMargin=30)
    elements = []
    styles = getSampleStyleSheet()
    
    # تنسيقات مخصصة
    title_style = ParagraphStyle('Title', parent=styles['Heading1'], fontSize=24, alignment=1, spaceAfter=20, textColor=colors.darkblue)
    sub_style = ParagraphStyle('Sub', parent=styles['Normal'], fontSize=12, alignment=1, spaceAfter=30)
    
    # 1. الترويسة (لوجو + صورة الموظف)
    logo_img = None
    staff_img = None
    
    if db.get("logo"):
        try:
            logo_bytes = base64.b64decode(db["logo"])
            logo_img = Image(io.BytesIO(logo_bytes), width=1.5*inch, height=1.5*inch)
        except: pass

    staff_data = db["users"].get(st.session_state['user'], {})
    if staff_data.get("photo"):
        try:
            staff_bytes = base64.b64decode(staff_data["photo"])
            staff_img = Image(io.BytesIO(staff_bytes), width=1.2*inch, height=1.2*inch)
        except: pass

    header_data = [[logo_img if logo_img else "", Paragraph(f"<b>NMS ENTERPRISE REPORT</b><br/>{branch}", title_style), staff_img if staff_img else ""]]
    header_table = Table(header_data, colWidths=[2*inch, 6*inch, 2*inch])
    header_table.setStyle(TableStyle([('ALIGN', (0,0), (-1,-1), 'CENTER'), ('VALIGN', (0,0), (-1,-1), 'MIDDLE')]))
    elements.append(header_table)
    elements.append(Spacer(1, 10))
    elements.append(Paragraph(f"Date: {date_str} | Generated By: {staff_name}", sub_style))

    # 2. الجدول المالي
    elements.append(Paragraph("💰 Financial Summary", styles['Heading2']))
    fin_data = [
        ["Item", "Value", "Notes"],
        ["Total Sales", f"{sales:,.2f}", "-"],
        ["Expenses", f"{expenses:,.2f}", exp_note],
        ["Opay Movement", f"{opay_move:,.2f}", "-"],
        ["Debit", f"{debit_v22:,.2f}", "Postponed"],
        ["NET DIFFERENCE", f"{diff:,.2f}", "Final Status"]
    ]
    fin_table = Table(fin_data, colWidths=[2.5*inch, 2.5*inch, 4*inch])
    fin_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.darkblue),
        ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke),
        ('ALIGN', (0,0), (-1,-1), 'CENTER'),
        ('GRID', (0,0), (-1,-1), 1, colors.black),
        ('BACKGROUND', (0,5), (-1,5), colors.lightgrey),
        ('FONTNAME', (0,5), (-1,5), 'Helvetica-Bold'),
    ]))
    elements.append(fin_table)
    elements.append(Spacer(1, 20))

 
# --- 4. Login Screen ---
if not st.session_state.get("logged_in", False):

    st.title("🔐 NMS Enterprise Access")

    c1, c2, c3 = st.columns([1,2,1])

    with c2:
        st.write("### 🔑 Secure Login")

        u = st.selectbox("Select Your Account", list(db["users"].keys()))
        p = st.text_input("Enter Password", type="password")

        if st.button("🚀 Login", use_container_width=True):
            if (
                u in db["users"]
                and "pass" in db["users"][u]
                and db["users"][u]["pass"] == p
            ):
                st.session_state.update({
                    'logged_in': True,
                    'user': u,
                    'role': db["users"][u]["role"]
                })

                if u in db.get("drafts", {}):
                    for key, val in db["drafts"][u].items():
                        st.session_state[key] = val

                db["logs"].append({
                    "user": u,
                    "time": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                    "action": "Login"
                })

                save_db(db)
                st.rerun()
            else:
                st.error("❌ Access Denied")

    st.stop()   # 🔥 هنا بس تحطه

# =========================
# من هنا يبدأ النظام بعد تسجيل الدخول
# =========================

else:
    # --- 5. Sidebar System ---
    with st.sidebar:
        user_info = db["users"][st.session_state['user']]
        if user_info.get("photo"): 
            st.image(base64.b64decode(user_info["photo"]), width=120)
        else:
            st.write("👤 No Photo")
            
        st.header(f"Hi, {user_info['full_name']}")
        
        # --- بوابة الموظف (Self-Service) ---
        if st.session_state['role'] == 'user':
            st.divider()
            st.subheader("📂 My Financial Profile")
            st.write(f"**📅 Hiring Date:** {user_info.get('hiring_date', '-')}")
            st.metric("💰 Base Salary", f"{user_info.get('salary', 0):,.2f} LE")
            
            with st.expander("🎁 My Bonuses", expanded=False):
                if user_info['bonus']: st.dataframe(pd.DataFrame(user_info['bonus']))
                else: st.info("No bonuses yet.")
                    
            with st.expander("⏳ Overtime", expanded=False):
                if user_info['overtime']: st.dataframe(pd.DataFrame(user_info['overtime']))
                else: st.info("No overtime yet.")
                    
            with st.expander("⚠️ My Deductions", expanded=False):
                if user_info['deductions']: st.dataframe(pd.DataFrame(user_info['deductions']))
                else: st.success("Clean Record! No deductions.")
                    
            with st.expander("🏖️ Extra Leave", expanded=False):
                if user_info['extra_leaves']: st.dataframe(pd.DataFrame(user_info['extra_leaves']))
                else: st.success("Clean Record! No extra_leaves.")
                    
        if st.button("🚪 Logout", use_container_width=True):
            st.session_state['logged_in'] = False; st.rerun()
        
        # --- صلاحيات المدير المطلقة (Master Control) ---
        if st.session_state.get('role') == 'admin':
            st.divider()
            st.subheader("⚙️ Admin Authority")
        
            admin_choice = st.selectbox(
                "Select Management Module:",
                [
                    "👥 Manage Employees (HR)", 
                    "💰 Payroll & Money", 
                    "📝 Tasks & Checklists", 
                    "🏢 Branches & Expenses",
                    "🖨 Printer Management",
                    "📂 Archive & History",
                    "🎓 Employee Training"
                ]
            )
        
            if admin_choice == "👥 Manage Employees (HR)":
                from hr_service import hr_management_ui
                hr_management_ui(db)
            # 2. الرواتب والماليات
            elif admin_choice == "💰 Payroll & Money":
                st.info("Manage Salaries, Bonuses & Deductions")
                target = st.selectbox("Select Employee", list(db["users"].keys()))
                u_fin = db["users"][target]
                
                col_s1, col_s2 = st.columns(2)
                with col_s1: sal = st.number_input("Base Salary", value=float(u_fin.get('salary', 0)))
                with col_s2: hire = st.date_input("Hiring Date", value=datetime.strptime(u_fin.get('hiring_date', "2024-01-01"), "%Y-%m-%d"))
                if st.button("💾 Update Contract"):
                    db["users"][target]["salary"] = sal
                    db["users"][target]["hiring_date"] = str(hire)
                    save_db(db); st.success("Contract Updated")
                
                st.divider()
                st.write("**Add Financial Entry:**")
                dev_type = st.radio("Type", ["Bonus 🎁", "Deductions ⚠️", "Overtime ⏳", "Extra Leave 🏖️"], horizontal=True)
                amt = st.number_input("Value (LE)", step=10.0)
                note = st.text_input("Reason / Note")
                if st.button("✅ Submit Entry"):
                    key = dev_type.split()[0].lower()
                    if key == "extra": key = "extra_leaves"
                    db["users"][target][key].append({"date": str(date.today()), "val": amt, "note": note})
                    save_db(db); st.success("Added to HR Record")

            # 3. إدارة المهام
            elif admin_choice == "📝 Tasks & Checklists":
                cat = st.selectbox("Category", ["opening", "closing", "social", "interaction"])
                for i, t in enumerate(db["tasks"][cat]):
                    c1, c2 = st.columns([5, 1])
                    c1.text(f"📌 {t}")
                    if c2.button("🗑️", key=f"del_t_{cat}_{i}"):
                        db["tasks"][cat].pop(i); save_db(db); st.rerun()
                new_t = st.text_input("New Task")
                if st.button("➕ Add Task"):
                    if new_t: db["tasks"][cat].append(new_t); save_db(db); st.rerun()
                        
            # 4. الفروع والمصاريف
            elif admin_choice == "🏢 Branches & Expenses":
                st.info("Manage Locations & Expenses")
                
                st.write("**🏢 Branches (الفروع)**")
                br_sel = st.selectbox("Select Branch", db["branches"])
                c_br1, c_br2 = st.columns(2)
                with c_br1:
                    new_br_name = st.text_input("Rename Branch", value=br_sel)
                    if st.button("✏️ Rename"):
                        idx = db["branches"].index(br_sel)
                        db["branches"][idx] = new_br_name
                        save_db(db); st.success("Renamed!"); st.rerun()
                with c_br2:
                    if st.button("🗑️ Delete Branch", type="primary"):
                        db["branches"].remove(br_sel)
                        save_db(db); st.warning("Deleted!"); st.rerun()
                
                new_b_add = st.text_input("New Branch Name")
                if st.button("➕ Create Branch"):
                    if new_b_add: db["branches"].append(new_b_add); save_db(db); st.rerun()

                st.divider()
                st.write("**💸 Expense Categories (بنود المصاريف)**")
                for i, e in enumerate(db["expense_categories"]):
                    ce1, ce2 = st.columns([5,1]); ce1.text(f"🔹 {e}")
                    if ce2.button("✖️", key=f"del_ex_{i}"): db["expense_categories"].pop(i); save_db(db); st.rerun()
                new_ex = st.text_input("New Expense Category")
                if st.button("➕ Add Expense Category"):
                    if new_ex: db["expense_categories"].append(new_ex); save_db(db); st.rerun()

            elif admin_choice == "📂 Archive & History":
                st.header("📂 Archive & History")
                
                # التأكد من صلاحية الأدمن (حسب نظامك)
                if st.session_state.get('role') != 'admin':
                    st.error("Access Denied: Admins Only.")
                    pass
            
                st.divider()
                
                # التحقق من وجود بيانات في الهيستوري
                if not db.get("history") or len(db["history"]) == 0:
                    st.info("No archived shifts found yet.")
                else:
                    # 1. Dashboard Metrics (إحصائيات سريعة)
                    h_data = db["history"]
                    
                    # استخدام try-except أو التحويل الآمن لضمان عدم حدوث خطأ لو القيمة نصية
                    try:
                        total_sales = sum(float(item.get('sales', 0)) for item in h_data)
                        total_exp = sum(float(item.get('expenses', 0)) for item in h_data)
                        total_diff = sum(float(item.get('diff', 0)) for item in h_data)
                    except ValueError:
                        st.error("Error in data types within History. Please check database.")
                        total_sales = total_exp = total_diff = 0
            
                    m1, m2, m3 = st.columns(3)
                    m1.metric("Total Sales", f"{total_sales:,.2f} LE")
                    m2.metric("Total Expenses", f"{total_exp:,.2f} LE")
                    m3.metric("Net Cash Diff", f"{total_diff:,.2f} LE", delta=total_diff, delta_color="normal")
            
                    st.divider()
            
                    # 2. Detailed Data Table (عرض الجدول)
                    st.subheader("📜 Detailed Shift History")
                    
                    # تحويل البيانات لـ DataFrame لسهولة العرض
                    df_history = pd.DataFrame(reversed(h_data))
                    
                    # خريطة تسمية الأعمدة لتناسب الكود الخاص بك
                    column_mapping = {
                        "date": "Date",
                        "staff": "Employee",
                        "branch": "Branch",
                        "sales": "Sales",
                        "expenses": "Expenses",
                        "exp_note": "Exp. Details",
                        "diff": "Cash Diff",
                        "kyo_jam": "Kyo Jam",
                        "xerox_jam": "Xerox Jam"
                    }
                    
                    # فلترة الأعمدة الموجودة فعلياً في الـ DataFrame فقط لتجنب الأخطاء
                    existing_columns = {k: v for k, v in column_mapping.items() if k in df_history.columns}
                    
                    st.dataframe(
                        df_history.rename(columns=existing_columns),
                        use_container_width=True,
                        column_config={
                            "Sales": st.column_config.NumberColumn(format="%.2f LE"),
                            "Expenses": st.column_config.NumberColumn(format="%.2f LE"),
                            "Cash Diff": st.column_config.NumberColumn(format="%.2f LE"),
                        }
                    )
            
                    # 3. Quick Actions (عمليات الحذف والتأمين)
                    st.divider()
                    with st.expander("🗑️ Advanced Settings (Danger Zone)"):
                        st.warning("Action below is irreversible!")
                        confirm_check = st.checkbox("I understand that 'Clear History' will delete everything.")
                        if confirm_check:
                            if st.button("🚨 Permanently Clear All History"):
                                db["history"] = []
                                save_db(db)
                                st.success("History Cleared!")
                                st.rerun()  
                                
            elif admin_choice == "🎓 Employee Training":
            
                st.markdown(
                    """
                    <style>
                    .training-title {
                        font-size: 36px;
                        font-weight: bold;
                        text-align: center;
                        color: #0F172A;
                        margin-bottom: 20px;
                    }
            
                    .training-card {
                        padding: 20px;
                        border-radius: 15px;
                        background: #F8FAFC;
                        box-shadow: 0px 4px 12px rgba(0,0,0,0.05);
                        margin-bottom: 20px;
                    }
            
                    .section-header {
                        font-size: 20px;
                        font-weight: bold;
                        color: #1E3A8A;
                        border-left: 6px solid #1E3A8A;
                        padding-left: 10px;
                        margin-bottom: 10px;
                    }
            
                    .highlight-box {
                        padding: 15px;
                        background: #EFF6FF;
                        border-radius: 10px;
                        font-weight: 500;
                    }
                    </style>
                    """,
                    unsafe_allow_html=True
                )
            
                st.markdown("🚀")
                st.markdown("<div class='training-title'>NMS Enterprise | Professional Training Center</div>", unsafe_allow_html=True)
            
                tabs = st.tabs([
                    "📜 Professional Standards",
                    "⚙ Technical Operations",
                    "🤝 Customer Excellence",
                    "💻 Digital Transformation"
                ])
            
                # ==============================
                # TAB 1 – Professional Standards
                # ==============================
                with tabs[0]:
            
                    st.markdown("<div class='training-card'>", unsafe_allow_html=True)
                    st.markdown("<div class='section-header'>🎯 Workplace Commitment</div>", unsafe_allow_html=True)
            
                    col1, col2 = st.columns(2)
            
                    with col1:
                        st.markdown("""
                        🔵 **Attendance**
                        - Arrive 15 minutes early
                        - Proper handover before shift
                        - Biometric logging mandatory
                        """)
            
                    with col2:
                        st.markdown("""
                        🔵 **Financial Responsibility**
                        - No printing without system record
                        - 50% minimum deposit policy
                        - Employee responsible for cash shortage
                        """)
            
                    st.markdown("</div>", unsafe_allow_html=True)
            
                # ==============================
                # TAB 2 – Technical Operations
                # ==============================
                with tabs[1]:
            
                    st.markdown("<div class='training-card'>", unsafe_allow_html=True)
                    st.markdown("<div class='section-header'>🖨 Equipment Handling</div>", unsafe_allow_html=True)
            
                    with st.expander("📠 Printer Operation"):
                        st.markdown("""
                        ✅ Check voltage before power-on  
                        ✅ Clear paper jam carefully  
                        ✅ Monitor print quality every 100 pages  
                        """)
            
                    with st.expander("✂ Finishing Equipment"):
                        st.markdown("""
                        ✅ Thermal binding – wait for green light  
                        ✅ Paper cutting – follow safety rules  
                        ✅ Spiral binding – choose correct size  
                        """)
            
                    st.markdown("</div>", unsafe_allow_html=True)
            
                # ==============================
                # TAB 3 – Customer Excellence
                # ==============================
                with tabs[2]:
            
                    st.markdown("<div class='training-card'>", unsafe_allow_html=True)
                    st.markdown("<div class='section-header'>🌟 Service Excellence Model</div>", unsafe_allow_html=True)
            
                    st.markdown("""
                    🟢 Greet with professionalism  
                    🟢 Listen without interruption  
                    🟢 Confirm before final delivery  
                    🟢 Resolve complaints calmly  
                    """)
            
                    st.markdown("<div class='highlight-box'>💡 Remember: Customer trust = Business growth</div>",
                                unsafe_allow_html=True)
            
                    st.markdown("</div>", unsafe_allow_html=True)
            
                # ==============================
                # TAB 4 – Digital Transformation
                # ==============================
                with tabs[3]:
            
                    st.markdown("<div class='training-card'>", unsafe_allow_html=True)
                    st.markdown("<div class='section-header'>🚀 Modern Tools</div>", unsafe_allow_html=True)
            
                    c1, c2, c3 = st.columns(3)
            
                    with c1:
                        st.image("https://img.icons8.com/color/96/canva.png", width=60)
                        st.markdown("**Canva**\nDesign & Social Media Content")
            
                    with c2:
                        st.image("https://img.icons8.com/color/96/chatgpt.png", width=60)
                        st.markdown("**AI Tools**\nSmart Automation & Text Optimization")
            
                    with c3:
                        st.image("https://img.icons8.com/color/96/microsoft-excel-2019.png", width=60)
                        st.markdown("**Office Tools**\nData & Reporting Mastery")
            
                    st.markdown("</div>", unsafe_allow_html=True)
            
                # ==============================
                # TRAINING ACKNOWLEDGEMENT
                # ==============================
            
                st.divider()
            
                st.markdown("### 📝 Training Acknowledgement")
            
                agree = st.checkbox(
                    "I confirm that I have completed the training and understood all policies."
                )
            
                if st.button("✅ Confirm Completion", use_container_width=True):
            
                    if agree:
                        st.success(f"Training Completed ✔ Recorded for {st.session_state.get('user')}")
                        st.balloons()
            
                        # يمكنك هنا تسجيل الموافقة في قاعدة البيانات
                        db["training_records"] = db.get("training_records", {})
                        db["training_records"][st.session_state.get("user")] = {
                            "date": str(date.today()),
                            "status": "completed"
                        }
            
                        save_db(db)
            
                    else:
                        st.warning("Please confirm the checkbox first.")
            elif admin_choice == "🖨 Printer Management":
                from printer_service import printer_management_ui
                printer_management_ui(db)

    
if st.session_state.get("role") == "admin":

    with st.expander("🧰 Backup Manager"):
        backup_folder = "backups"

        if not os.path.exists(backup_folder) or len(os.listdir(backup_folder)) == 0:
            st.warning("لا توجد نسخ احتياطية حتى الآن.")

        else:
            backup_files = sorted(os.listdir(backup_folder), reverse=True)
            latest_file = backup_files[0]
            latest_path = os.path.join(backup_folder, latest_file)

            st.info(f"🕒 أحدث نسخة: {latest_file}")

            with open(latest_path, "rb") as f:
                st.download_button("📥 تحميل النسخة الاحتياطية",
                                   f,
                                   file_name=latest_file)

    # ✅ ده بره expander لكن جوه admin
    st.markdown("### ♻️ استرجاع نسخة قديمة")

    if not os.path.exists(backup_folder):
        os.makedirs(backup_folder)

    restore_file = st.selectbox(
        "اختر نسخة احتياطية",
        os.listdir(backup_folder)
    )

    if st.button("♻️ استرجاع النسخة المحددة"):
        selected_path = os.path.join(backup_folder, restore_file)
        with open(selected_path, "r", encoding="utf-8") as f:
            restored_data = json.load(f)

        save_db(restored_data)
        st.success("✅ تم استرجاع النسخة بنجاح")

from operations_service import daily_operations_ui

if st.session_state.get("logged_in"):
    daily_operations_ui(db)

