import streamlit as st
import pandas as pd
from datetime import datetime, date
import json
import os
import io
import base64
import urllib.parse
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter, landscape
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from printer_service import PRINTERS, calculate_printer_difference
# --- 1. إعدادات قاعدة البيانات (Database Configuration) ---
from database import load_db, save_db, MANAGER_PHONE
db = load_db()
def sync_draft():
    if st.session_state.get("logged_in"):
        user = st.session_state.get("user")
        if not user:
            return

        draft_keys = (
            's_','o_','e_','c_','m_','i_',
            'ks','xs','op','u10','v22','ex',
            'kj','xj','dn','k1','k2','x1','x2'
        )

        draft_data = {
            k: v
            for k, v in st.session_state.items()
            if k.startswith(draft_keys)
        }

        if "drafts" not in db:
            db["drafts"] = {}

        db["drafts"][user] = draft_data
        save_db(db)
if "users" not in db:
    db["users"] = {}
    save_db(db)



# --- 2. Advanced PDF Generation (تقرير شامل) ---
def create_downloadable_pdf(branch, staff_name, date_str, sales, expenses, exp_note, diff, kyo_data, xerox_data, opay_move, debit_v22):
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=landscape(letter), topMargin=30, bottomMargin=30)
    elements = []
    styles = getSampleStyleSheet()
    
    # تنسيقات مخصصة
    title_style = ParagraphStyle('Title', parent=styles['Heading1'], fontSize=24, alignment=1, spaceAfter=20, textColor=colors.darkblue)
    sub_style = ParagraphStyle('Sub', parent=styles['Normal'], fontSize=12, alignment=1, spaceAfter=30)
    
    # 1. الترويسة (لوجو + صورة الموظف)
    logo_img = None
    staff_img = None
    
    if db.get("logo"):
        try:
            logo_bytes = base64.b64decode(db["logo"])
            logo_img = Image(io.BytesIO(logo_bytes), width=1.5*inch, height=1.5*inch)
        except: pass

    staff_data = db["users"].get(st.session_state['user'], {})
    if staff_data.get("photo"):
        try:
            staff_bytes = base64.b64decode(staff_data["photo"])
            staff_img = Image(io.BytesIO(staff_bytes), width=1.2*inch, height=1.2*inch)
        except: pass

    header_data = [[logo_img if logo_img else "", Paragraph(f"<b>NMS ENTERPRISE REPORT</b><br/>{branch}", title_style), staff_img if staff_img else ""]]
    header_table = Table(header_data, colWidths=[2*inch, 6*inch, 2*inch])
    header_table.setStyle(TableStyle([('ALIGN', (0,0), (-1,-1), 'CENTER'), ('VALIGN', (0,0), (-1,-1), 'MIDDLE')]))
    elements.append(header_table)
    elements.append(Spacer(1, 10))
    elements.append(Paragraph(f"Date: {date_str} | Generated By: {staff_name}", sub_style))

    # 2. الجدول المالي
    elements.append(Paragraph("💰 Financial Summary", styles['Heading2']))
    fin_data = [
        ["Item", "Value", "Notes"],
        ["Total Sales", f"{sales:,.2f}", "-"],
        ["Expenses", f"{expenses:,.2f}", exp_note],
        ["Opay Movement", f"{opay_move:,.2f}", "-"],
        ["Debit", f"{debit_v22:,.2f}", "Postponed"],
        ["NET DIFFERENCE", f"{diff:,.2f}", "Final Status"]
    ]
    fin_table = Table(fin_data, colWidths=[2.5*inch, 2.5*inch, 4*inch])
    fin_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.darkblue),
        ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke),
        ('ALIGN', (0,0), (-1,-1), 'CENTER'),
        ('GRID', (0,0), (-1,-1), 1, colors.black),
        ('BACKGROUND', (0,5), (-1,5), colors.lightgrey),
        ('FONTNAME', (0,5), (-1,5), 'Helvetica-Bold'),
    ]))
    elements.append(fin_table)
    elements.append(Spacer(1, 20))

 
# --- 4. Login Screen ---
if not st.session_state.get("logged_in", False):

    st.title("🔐 NMS Enterprise Access")

    c1, c2, c3 = st.columns([1,2,1])

    with c2:
        st.write("### 🔑 Secure Login")

        u = st.selectbox("Select Your Account", list(db["users"].keys()))
        p = st.text_input("Enter Password", type="password")

        if st.button("🚀 Login", use_container_width=True):
            if (
                u in db["users"]
                and "pass" in db["users"][u]
                and db["users"][u]["pass"] == p
            ):
                st.session_state.update({
                    'logged_in': True,
                    'user': u,
                    'role': db["users"][u]["role"]
                })

                if u in db.get("drafts", {}):
                    for key, val in db["drafts"][u].items():
                        st.session_state[key] = val

                db["logs"].append({
                    "user": u,
                    "time": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                    "action": "Login"
                })

                save_db(db)
                st.rerun()
            else:
                st.error("❌ Access Denied")

    st.stop()   # 🔥 هنا بس تحطه

# =========================
# من هنا يبدأ النظام بعد تسجيل الدخول
# =========================

else:
    # --- 5. Sidebar System ---
    with st.sidebar:
        user_info = db["users"][st.session_state['user']]
        if user_info.get("photo"): 
            st.image(base64.b64decode(user_info["photo"]), width=120)
        else:
            st.write("👤 No Photo")
            
        st.header(f"Hi, {user_info['full_name']}")
        
        # --- بوابة الموظف (Self-Service) ---
        if st.session_state['role'] == 'user':
            st.divider()
            st.subheader("📂 My Financial Profile")
            st.write(f"**📅 Hiring Date:** {user_info.get('hiring_date', '-')}")
            st.metric("💰 Base Salary", f"{user_info.get('salary', 0):,.2f} LE")
            
            with st.expander("🎁 My Bonuses", expanded=False):
                if user_info['bonus']: st.dataframe(pd.DataFrame(user_info['bonus']))
                else: st.info("No bonuses yet.")
                    
            with st.expander("⏳ Overtime", expanded=False):
                if user_info['overtime']: st.dataframe(pd.DataFrame(user_info['overtime']))
                else: st.info("No overtime yet.")
                    
            with st.expander("⚠️ My Deductions", expanded=False):
                if user_info['deductions']: st.dataframe(pd.DataFrame(user_info['deductions']))
                else: st.success("Clean Record! No deductions.")
                    
            with st.expander("🏖️ Extra Leave", expanded=False):
                if user_info['extra_leaves']: st.dataframe(pd.DataFrame(user_info['extra_leaves']))
                else: st.success("Clean Record! No extra_leaves.")
                    
        if st.button("🚪 Logout", use_container_width=True):
            st.session_state['logged_in'] = False; st.rerun()
        
        # --- صلاحيات المدير المطلقة (Master Control) ---
        if st.session_state.get('role') == 'admin':
            st.divider()
            st.subheader("⚙️ Admin Authority")
        
            admin_choice = st.selectbox(
                "Select Management Module:",
                [
                    "👥 Manage Employees (HR)", 
                    "💰 Payroll & Money", 
                    "📝 Tasks & Checklists", 
                    "🏢 Branches & Expenses",
                    "🖨 Printer Management",
                    "📂 Archive & History",
                    "🎓 Employee Training"
                ]
            )
        
            if admin_choice == "👥 Manage Employees (HR)":
                from hr_service import hr_management_ui
                hr_management_ui(db)
            # 2. الرواتب والماليات
            elif admin_choice == "💰 Payroll & Money":
                st.info("Manage Salaries, Bonuses & Deductions")
                target = st.selectbox("Select Employee", list(db["users"].keys()))
                u_fin = db["users"][target]
                
                col_s1, col_s2 = st.columns(2)
                with col_s1: sal = st.number_input("Base Salary", value=float(u_fin.get('salary', 0)))
                with col_s2: hire = st.date_input("Hiring Date", value=datetime.strptime(u_fin.get('hiring_date', "2024-01-01"), "%Y-%m-%d"))
                if st.button("💾 Update Contract"):
                    db["users"][target]["salary"] = sal
                    db["users"][target]["hiring_date"] = str(hire)
                    save_db(db); st.success("Contract Updated")
                
                st.divider()
                st.write("**Add Financial Entry:**")
                dev_type = st.radio("Type", ["Bonus 🎁", "Deductions ⚠️", "Overtime ⏳", "Extra Leave 🏖️"], horizontal=True)
                amt = st.number_input("Value (LE)", step=10.0)
                note = st.text_input("Reason / Note")
                if st.button("✅ Submit Entry"):
                    key = dev_type.split()[0].lower()
                    if key == "extra": key = "extra_leaves"
                    db["users"][target][key].append({"date": str(date.today()), "val": amt, "note": note})
                    save_db(db); st.success("Added to HR Record")

            # 3. إدارة المهام
            elif admin_choice == "📝 Tasks & Checklists":
                cat = st.selectbox("Category", ["opening", "closing", "social", "interaction"])
                for i, t in enumerate(db["tasks"][cat]):
                    c1, c2 = st.columns([5, 1])
                    c1.text(f"📌 {t}")
                    if c2.button("🗑️", key=f"del_t_{cat}_{i}"):
                        db["tasks"][cat].pop(i); save_db(db); st.rerun()
                new_t = st.text_input("New Task")
                if st.button("➕ Add Task"):
                    if new_t: db["tasks"][cat].append(new_t); save_db(db); st.rerun()
                        
            # 4. الفروع والمصاريف
            elif admin_choice == "🏢 Branches & Expenses":
                st.info("Manage Locations & Expenses")
                
                st.write("**🏢 Branches (الفروع)**")
                br_sel = st.selectbox("Select Branch", db["branches"])
                c_br1, c_br2 = st.columns(2)
                with c_br1:
                    new_br_name = st.text_input("Rename Branch", value=br_sel)
                    if st.button("✏️ Rename"):
                        idx = db["branches"].index(br_sel)
                        db["branches"][idx] = new_br_name
                        save_db(db); st.success("Renamed!"); st.rerun()
                with c_br2:
                    if st.button("🗑️ Delete Branch", type="primary"):
                        db["branches"].remove(br_sel)
                        save_db(db); st.warning("Deleted!"); st.rerun()
                
                new_b_add = st.text_input("New Branch Name")
                if st.button("➕ Create Branch"):
                    if new_b_add: db["branches"].append(new_b_add); save_db(db); st.rerun()

                st.divider()
                st.write("**💸 Expense Categories (بنود المصاريف)**")
                for i, e in enumerate(db["expense_categories"]):
                    ce1, ce2 = st.columns([5,1]); ce1.text(f"🔹 {e}")
                    if ce2.button("✖️", key=f"del_ex_{i}"): db["expense_categories"].pop(i); save_db(db); st.rerun()
                new_ex = st.text_input("New Expense Category")
                if st.button("➕ Add Expense Category"):
                    if new_ex: db["expense_categories"].append(new_ex); save_db(db); st.rerun()

            elif admin_choice == "📂 Archive & History":
                st.header("📂 Archive & History")
                
                # التأكد من صلاحية الأدمن (حسب نظامك)
                if st.session_state.get('role') != 'admin':
                    st.error("Access Denied: Admins Only.")
                    pass
            
                st.divider()
                
                # التحقق من وجود بيانات في الهيستوري
                if not db.get("history") or len(db["history"]) == 0:
                    st.info("No archived shifts found yet.")
                else:
                    # 1. Dashboard Metrics (إحصائيات سريعة)
                    h_data = db["history"]
                    
                    # استخدام try-except أو التحويل الآمن لضمان عدم حدوث خطأ لو القيمة نصية
                    try:
                        total_sales = sum(float(item.get('sales', 0)) for item in h_data)
                        total_exp = sum(float(item.get('expenses', 0)) for item in h_data)
                        total_diff = sum(float(item.get('diff', 0)) for item in h_data)
                    except ValueError:
                        st.error("Error in data types within History. Please check database.")
                        total_sales = total_exp = total_diff = 0
            
                    m1, m2, m3 = st.columns(3)
                    m1.metric("Total Sales", f"{total_sales:,.2f} LE")
                    m2.metric("Total Expenses", f"{total_exp:,.2f} LE")
                    m3.metric("Net Cash Diff", f"{total_diff:,.2f} LE", delta=total_diff, delta_color="normal")
            
                    st.divider()
            
                    # 2. Detailed Data Table (عرض الجدول)
                    st.subheader("📜 Detailed Shift History")
                    
                    # تحويل البيانات لـ DataFrame لسهولة العرض
                    df_history = pd.DataFrame(reversed(h_data))
                    
                    # خريطة تسمية الأعمدة لتناسب الكود الخاص بك
                    column_mapping = {
                        "date": "Date",
                        "staff": "Employee",
                        "branch": "Branch",
                        "sales": "Sales",
                        "expenses": "Expenses",
                        "exp_note": "Exp. Details",
                        "diff": "Cash Diff",
                        "kyo_jam": "Kyo Jam",
                        "xerox_jam": "Xerox Jam"
                    }
                    
                    # فلترة الأعمدة الموجودة فعلياً في الـ DataFrame فقط لتجنب الأخطاء
                    existing_columns = {k: v for k, v in column_mapping.items() if k in df_history.columns}
                    
                    st.dataframe(
                        df_history.rename(columns=existing_columns),
                        use_container_width=True,
                        column_config={
                            "Sales": st.column_config.NumberColumn(format="%.2f LE"),
                            "Expenses": st.column_config.NumberColumn(format="%.2f LE"),
                            "Cash Diff": st.column_config.NumberColumn(format="%.2f LE"),
                        }
                    )
            
                    # 3. Quick Actions (عمليات الحذف والتأمين)
                    st.divider()
                    with st.expander("🗑️ Advanced Settings (Danger Zone)"):
                        st.warning("Action below is irreversible!")
                        confirm_check = st.checkbox("I understand that 'Clear History' will delete everything.")
                        if confirm_check:
                            if st.button("🚨 Permanently Clear All History"):
                                db["history"] = []
                                save_db(db)
                                st.success("History Cleared!")
                                st.rerun()  
                                
            elif admin_choice == "🎓 Employee Training":
            
                st.markdown(
                    """
                    <style>
                    .training-title {
                        font-size: 36px;
                        font-weight: bold;
                        text-align: center;
                        color: #0F172A;
                        margin-bottom: 20px;
                    }
            
                    .training-card {
                        padding: 20px;
                        border-radius: 15px;
                        background: #F8FAFC;
                        box-shadow: 0px 4px 12px rgba(0,0,0,0.05);
                        margin-bottom: 20px;
                    }
            
                    .section-header {
                        font-size: 20px;
                        font-weight: bold;
                        color: #1E3A8A;
                        border-left: 6px solid #1E3A8A;
                        padding-left: 10px;
                        margin-bottom: 10px;
                    }
            
                    .highlight-box {
                        padding: 15px;
                        background: #EFF6FF;
                        border-radius: 10px;
                        font-weight: 500;
                    }
                    </style>
                    """,
                    unsafe_allow_html=True
                )
            
                st.markdown("🚀")
                st.markdown("<div class='training-title'>NMS Enterprise | Professional Training Center</div>", unsafe_allow_html=True)
            
                tabs = st.tabs([
                    "📜 Professional Standards",
                    "⚙ Technical Operations",
                    "🤝 Customer Excellence",
                    "💻 Digital Transformation"
                ])
            
                # ==============================
                # TAB 1 – Professional Standards
                # ==============================
                with tabs[0]:
            
                    st.markdown("<div class='training-card'>", unsafe_allow_html=True)
                    st.markdown("<div class='section-header'>🎯 Workplace Commitment</div>", unsafe_allow_html=True)
            
                    col1, col2 = st.columns(2)
            
                    with col1:
                        st.markdown("""
                        🔵 **Attendance**
                        - Arrive 15 minutes early
                        - Proper handover before shift
                        - Biometric logging mandatory
                        """)
            
                    with col2:
                        st.markdown("""
                        🔵 **Financial Responsibility**
                        - No printing without system record
                        - 50% minimum deposit policy
                        - Employee responsible for cash shortage
                        """)
            
                    st.markdown("</div>", unsafe_allow_html=True)
            
                # ==============================
                # TAB 2 – Technical Operations
                # ==============================
                with tabs[1]:
            
                    st.markdown("<div class='training-card'>", unsafe_allow_html=True)
                    st.markdown("<div class='section-header'>🖨 Equipment Handling</div>", unsafe_allow_html=True)
            
                    with st.expander("📠 Printer Operation"):
                        st.markdown("""
                        ✅ Check voltage before power-on  
                        ✅ Clear paper jam carefully  
                        ✅ Monitor print quality every 100 pages  
                        """)
            
                    with st.expander("✂ Finishing Equipment"):
                        st.markdown("""
                        ✅ Thermal binding – wait for green light  
                        ✅ Paper cutting – follow safety rules  
                        ✅ Spiral binding – choose correct size  
                        """)
            
                    st.markdown("</div>", unsafe_allow_html=True)
            
                # ==============================
                # TAB 3 – Customer Excellence
                # ==============================
                with tabs[2]:
            
                    st.markdown("<div class='training-card'>", unsafe_allow_html=True)
                    st.markdown("<div class='section-header'>🌟 Service Excellence Model</div>", unsafe_allow_html=True)
            
                    st.markdown("""
                    🟢 Greet with professionalism  
                    🟢 Listen without interruption  
                    🟢 Confirm before final delivery  
                    🟢 Resolve complaints calmly  
                    """)
            
                    st.markdown("<div class='highlight-box'>💡 Remember: Customer trust = Business growth</div>",
                                unsafe_allow_html=True)
            
                    st.markdown("</div>", unsafe_allow_html=True)
            
                # ==============================
                # TAB 4 – Digital Transformation
                # ==============================
                with tabs[3]:
            
                    st.markdown("<div class='training-card'>", unsafe_allow_html=True)
                    st.markdown("<div class='section-header'>🚀 Modern Tools</div>", unsafe_allow_html=True)
            
                    c1, c2, c3 = st.columns(3)
            
                    with c1:
                        st.image("https://img.icons8.com/color/96/canva.png", width=60)
                        st.markdown("**Canva**\nDesign & Social Media Content")
            
                    with c2:
                        st.image("https://img.icons8.com/color/96/chatgpt.png", width=60)
                        st.markdown("**AI Tools**\nSmart Automation & Text Optimization")
            
                    with c3:
                        st.image("https://img.icons8.com/color/96/microsoft-excel-2019.png", width=60)
                        st.markdown("**Office Tools**\nData & Reporting Mastery")
            
                    st.markdown("</div>", unsafe_allow_html=True)
            
                # ==============================
                # TRAINING ACKNOWLEDGEMENT
                # ==============================
            
                st.divider()
            
                st.markdown("### 📝 Training Acknowledgement")
            
                agree = st.checkbox(
                    "I confirm that I have completed the training and understood all policies."
                )
            
                if st.button("✅ Confirm Completion", use_container_width=True):
            
                    if agree:
                        st.success(f"Training Completed ✔ Recorded for {st.session_state.get('user')}")
                        st.balloons()
            
                        # يمكنك هنا تسجيل الموافقة في قاعدة البيانات
                        db["training_records"] = db.get("training_records", {})
                        db["training_records"][st.session_state.get("user")] = {
                            "date": str(date.today()),
                            "status": "completed"
                        }
            
                        save_db(db)
            
                    else:
                        st.warning("Please confirm the checkbox first.")
            elif admin_choice == "🖨 Printer Management":
                from printer_service import printer_management_ui
                printer_management_ui(db, PRINTERS)

    
if st.session_state.get("role") == "admin":

    with st.expander("🧰 Backup Manager"):
        backup_folder = "backups"

        if not os.path.exists(backup_folder) or len(os.listdir(backup_folder)) == 0:
            st.warning("لا توجد نسخ احتياطية حتى الآن.")

        else:
            backup_files = sorted(os.listdir(backup_folder), reverse=True)
            latest_file = backup_files[0]
            latest_path = os.path.join(backup_folder, latest_file)

            st.info(f"🕒 أحدث نسخة: {latest_file}")

            with open(latest_path, "rb") as f:
                st.download_button("📥 تحميل النسخة الاحتياطية",
                                   f,
                                   file_name=latest_file)

    # ✅ ده بره expander لكن جوه admin
    st.markdown("### ♻️ استرجاع نسخة قديمة")

    if not os.path.exists(backup_folder):
        os.makedirs(backup_folder)

    restore_file = st.selectbox(
        "اختر نسخة احتياطية",
        os.listdir(backup_folder)
    )

    if st.button("♻️ استرجاع النسخة المحددة"):
        selected_path = os.path.join(backup_folder, restore_file)
        with open(selected_path, "r", encoding="utf-8") as f:
            restored_data = json.load(f)

        save_db(restored_data)
        st.success("✅ تم استرجاع النسخة بنجاح")
# --- 6. Main Dashboard: DAILY OPERATIONS ---
st.title("📊 NMS ERP - Daily Operations")

# ✅ حفظ الفرع في session_state
if "branch" not in st.session_state:
    st.session_state["branch"] = db["branches"][0]

if "shift" not in st.session_state:
    st.session_state["shift"] = "Morning"

m1, m2, m3, m4 = st.columns(4)

with m1:
    st.session_state["branch"] = st.selectbox(
        "📍 Branch",
        db["branches"],
        index=db["branches"].index(st.session_state["branch"])
    )

with m2:
    st.session_state["shift"] = st.selectbox(
        "🕒 Shift",
        ["Morning", "Between", "Night"],
        index=["Morning", "Between", "Night"].index(st.session_state["shift"])
    )

with m3:
    st.info(f"📅 {datetime.now().strftime('%Y-%m-%d')}")

with m4:
    st.info(f"👤 {st.session_state['user']}")
# ========== LOGIN CHECK ==========
if "user" not in st.session_state:
    show_login()
    st.stop()

# ========== MAIN SYSTEM ==========
tab1, tab2, tab3 = st.tabs(["🟢 OPENING", "🔴 CLOSING", "📱 SOCIAL"])

with tab1:

    st.subheader("🌅 Opening Procedures")

    c_o1, c_o2, c_o3 = st.columns([1, 1.5, 1.5])

    with c_o1:
        st.markdown("#### ✅ Opening Tasks")
        for t in db["tasks"]["opening"]:
            st.checkbox(t, key=f"s_{t}", on_change=sync_draft)

    with c_o2:
        st.markdown("#### 💵 Cash Denominations (Opening)")
        t_open = 0.0
        for d in [200, 100, 50, 20, 10, 5]:
            v = st.number_input(f"{d} LE", min_value=0, step=1,
                                key=f"o_{d}", on_change=sync_draft)
            t_open += (v * d)

        o_coins = st.number_input("Coins", step=0.5,
                                  key="o_coins", on_change=sync_draft)
        t_open += o_coins

        st.success(f"**Total Opening: {t_open:,.2f} LE**")
        st.session_state["t_open"] = t_open

with c_o3:

    st.markdown("#### 🖨 Opening Printer Counters")

    printer_start = {}

    for printer in PRINTERS:
        st.markdown(f"##### {printer}")

        col1, col2 = st.columns(2)
        col3, col4, col5 = st.columns(3)

        with col1:
            total = st.number_input(
                f"{printer} Total",
                min_value=0,
                key=f"{printer}_start_total"
            )

        with col2:
            one_side = st.number_input(
                f"{printer} 1 Side",
                min_value=0,
                key=f"{printer}_start_one"
            )

        with col3:
            two_side = st.number_input(
                f"{printer} 2 Side",
                min_value=0,
                key=f"{printer}_start_two"
            )

        with col4:
            errors = st.number_input(
                f"{printer} Errors",
                min_value=0,
                key=f"{printer}_start_errors"
            )

        with col5:
            jam = st.number_input(
                f"{printer} Jam",
                min_value=0,
                key=f"{printer}_start_jam"
            )

        printer_start[printer] = {
            "Total": total,
            "One Side": one_side,
            "Two Side": two_side,
            "Errors": errors,
            "Jam": jam
        }

    st.session_state["printer_start"] = printer_start
    
    st.divider()
    
    ops = st.number_input(
        "Opay Start Balance",
        step=0.01,
        key="ops",
        on_change=sync_draft
    )

    u10 = st.number_input(
        "Debit",
        step=1.0,
        key="u10_val",
        on_change=sync_draft
    )
        

# --- TAB 2: CLOSING ---
with tab2:

    st.subheader("🌇 Closing Procedures")


    c_c1, c_c2, c_c3 = st.columns([1, 1.5, 1.5])

    with c_c1:
        st.markdown("#### ✅ Closing Tasks")
        for t in db["tasks"]["closing"]:
            st.checkbox(t, key=f"e_{t}", on_change=sync_draft)

        st.divider()

        st.markdown("#### 💳 System & Payments")
        sys_sales = st.number_input("💻 System Sales",
                                   step=1.0,
                                   key="c_sys_sales",
                                   on_change=sync_draft)

        insta = st.number_input("📱 Instapay",
                                step=1.0,
                                key="c_insta",
                                on_change=sync_draft)

        wall = st.number_input("👛 Wallet",
                               step=1.0,
                               key="c_wall",
                               on_change=sync_draft)

        visa = st.number_input("💳 Visa",
                               step=1.0,
                               key="c_visa",
                               on_change=sync_draft)

        v22 = st.number_input("📉 Debit",
                              step=1.0,
                              key="v22_val",
                              on_change=sync_draft)

        t_digital = insta + wall + visa

    with c_c2:

        st.markdown("#### 💵 Cash Denominations (Closing)")
        t_close = 0.0

        for d in [200, 100, 50, 20, 10, 5]:
            v = st.number_input(f"{d} LE ",
                                min_value=0,
                                step=1,
                                key=f"c_{d}",
                                on_change=sync_draft)
            t_close += (v * d)

        c_coins = st.number_input("Closing Coins",
                                  step=0.5,
                                  key="c_coins",
                                  on_change=sync_draft)

        t_close += c_coins

        st.divider()

        st.markdown("#### 💸 Expenses Detail")
        ex_cat = st.selectbox("Category",
                              db["expense_categories"],
                              key="ex_cat")

        ex_val = st.number_input("Amount",
                                 step=1.0,
                                 key="ex_val")

        ex_note = st.text_input("Details / Reason",
                                key="ex_note")

        expected = t_open + sys_sales + u10 - ex_val - v22 - t_digital
        diff = t_close - expected
        st.session_state["t_close"] = t_close
        st.session_state["cash_diff"] = diff

        st.metric("Expected Drawer", f"{expected:,.2f} LE")

        if abs(diff) < 0.1:
            st.success("✨ Perfect Match!")
        elif diff > 0:
            st.warning(f"➕ Surplus: {diff:,.2f}")
        else:
            st.error(f"➖ Shortage: {diff:,.2f}")

    with c_c3:
        st.markdown("#### 🖨 Closing Printer Counters")
    
        printer_end = {}
    
        for printer in PRINTERS:
    
            st.markdown(f"##### {printer}")
    
            col1, col2 = st.columns(2)
            col3, col4, col5 = st.columns(3)
    
            with col1:
                total = st.number_input(
                    f"{printer} Total",
                    min_value=0,
                    key=f"{printer}_end_total"
                )
    
            with col2:
                one_side = st.number_input(
                    f"{printer} 1 Side",
                    min_value=0,
                    key=f"{printer}_end_one"
                )
    
            with col3:
                two_side = st.number_input(
                    f"{printer} 2 Side",
                    min_value=0,
                    key=f"{printer}_end_two"
                )
    
            with col4:
                errors = st.number_input(
                    f"{printer} Errors",
                    min_value=0,
                    key=f"{printer}_end_errors"
                )
    
            with col5:
                jam = st.number_input(
                    f"{printer} Jam",
                    min_value=0,
                    key=f"{printer}_end_jam"
                )
    
            printer_end[printer] = {
                "Total": total,
                "One Side": one_side,
                "Two Side": two_side,
                "Errors": errors,
                "Jam": jam
            }
    
        st.session_state["printer_end"] = printer_end
    
        if st.button("📊 Calculate Printer Usage"):
            printer_diff = calculate_printer_difference(
                st.session_state.get("printer_start", {}),
                st.session_state.get("printer_end", {})
            )
    
            st.session_state["printer_diff"] = printer_diff
    
            st.success("✅ Printer Usage Calculated")
            st.json(printer_diff)
    
        ope = st.number_input("Opay End Balance",
                                step=0.01,
                                key="ope")
    
        st.write(f"📉 Opay Used: {ops - ope:,.2f}")
    
        st.text_area("📝 Draft Notes / Handover",
                        key="dn_notes",
                        on_change=sync_draft)
        
# --- TAB 3: SOCIAL ---
with tab3:

    st.subheader("📱 Marketing & Finalization")

    sc1, sc2 = st.columns(2)

    # =========================
    # SOCIAL TASKS
    # =========================
    with sc1:
        st.markdown("#### 📢 Social Media Tasks")
        for t in db["tasks"].get("social", []):
            st.checkbox(t, key=f"m_{t}", on_change=sync_draft)

    with sc2:
        st.markdown("#### ❤️ Interaction Tasks")
        for t in db["tasks"].get("interaction", []):
            st.checkbox(t, key=f"i_{t}", on_change=sync_draft)

    st.divider()
    st.write("### 🏁 End Shift Actions")

    # =====================================================
    # SAFE VARIABLES
    # =====================================================
    t_open = st.session_state.get("t_open", 0)
    t_close = st.session_state.get("t_close", 0)
    sys_sales = st.session_state.get("c_sys_sales", 0)
    ex_val = st.session_state.get("ex_val", 0)
    ex_cat = st.session_state.get("ex_cat", "-")
    ex_note = st.session_state.get("ex_note", "-")

    t_digital = (
        st.session_state.get("c_insta", 0)
        + st.session_state.get("c_wall", 0)
        + st.session_state.get("c_visa", 0)
    )

    diff = st.session_state.get("cash_diff", 0)

    # =========================
    # PRINTER SAFE VALUES
    # =========================

    # Kyocera
    _ks = st.session_state.get("ks", 0)
    _ke = st.session_state.get("ke", 0)
    _k1 = st.session_state.get("k1s_v", 0)
    _k2 = st.session_state.get("k2s_v", 0)

    # Xerox
    _xs = st.session_state.get("xs", 0)
    _xe = st.session_state.get("xe", 0)
    _x1 = st.session_state.get("x1s_v", 0)
    _x2 = st.session_state.get("x2s_v", 0)

    # HP (الطابعة التالتة)
    _hs = st.session_state.get("hs", 0)
    _he = st.session_state.get("he", 0)
    _h1 = st.session_state.get("h1s_v", 0)
    _h2 = st.session_state.get("h2s_v", 0)

    # =========================
    # CALCULATIONS
    # =========================

    kyo_used = _ke - _ks
    xerox_used = _xe - _xs
    hp_used = _he - _hs

    kyo_actual = _k1 + _k2
    xerox_actual = _x1 + _x2
    hp_actual = _h1 + _h2

    # =====================================================
    # TASK STATISTICS
    # =====================================================
    def count_tasks(prefix):
        tasks_list = db["tasks"].get(prefix, [])
        done = 0
        map_p = {
            "opening": "s_",
            "closing": "e_",
            "social": "m_",
            "interaction": "i_",
        }
        p = map_p.get(prefix, "")
        for t in tasks_list:
            if st.session_state.get(f"{p}{t}", False):
                done += 1
        return done, len(tasks_list)

    op_done, op_tot = count_tasks("opening")
    cl_done, cl_tot = count_tasks("closing")
    soc_done, soc_tot = count_tasks("social")
    int_done, int_tot = count_tasks("interaction")

    # =====================================================
    # DISCREPANCY CHECK
    # =====================================================
    error_notes = []

    if abs(diff) > 0.1:
        error_notes.append(f"⚠️ Cash Difference: {diff:,.2f}")

    kyo_reported = _k1 + (_k2 * 2) + st.session_state.get("kj_v", 0)
    if kyo_actual != kyo_reported:
        error_notes.append(
            f"⚠️ Kyocera Counter Diff: {kyo_reported} vs {kyo_actual}"
        )

    xerox_reported = _x1 + (_x2 * 2) + st.session_state.get("xj_v", 0)
    if xerox_actual != xerox_reported:
        error_notes.append(
            f"⚠️ Xerox Counter Diff: {xerox_reported} vs {xerox_actual}"
        )

    hp_reported = _h1 + (_h2 * 2) + st.session_state.get("hj_v", 0)
    if hp_actual != hp_reported:
        error_notes.append(
            f"⚠️ HP Counter Diff: {hp_reported} vs {hp_actual}"
        )

    notes_section = "\n".join(error_notes) if error_notes else "✅ No discrepancies found"

    # =====================================================
    # WHATSAPP MESSAGE
    # =====================================================
    branch = st.session_state.get("branch", "-")
    shift = st.session_state.get("shift", "-")
    
    wa_text = f"""*🚀 NMS ERP - SHIFT REPORT*
    ━━━━━━━━━━━━━━━━
    📅 Date: {date.today()}
    👤 Staff: {st.session_state.get('user')}
    📍 Branch: {branch}
    🕒 Shift: {shift}
    
    *💰 FINANCIAL SUMMARY*
    ━━━━━━━━━━━━━━━━
    💵 Opening Cash: {t_open:,.2f}
    💻 System Sales: {sys_sales:,.2f}
    💸 Expenses: {ex_val:,.2f} ({ex_cat}: {ex_note})
    💳 Digital Total: {t_digital:,.2f}
    💰 Closing Drawer: {t_close:,.2f}
    ⚖️ Net Difference: {diff:,.2f}
    
    *🖨️ PRINTER SUMMARY*
    ━━━━━━━━━━━━━━━━
    📠 Kyocera 3010i: {kyo_used}
    📠 Xerox 7835: {xerox_used}
    📠 Kyocera P5031DN: {hp_used}
    📱 Opay Used: {st.session_state.get('ops',0) - st.session_state.get('ope',0):,.2f}
    
    *✅ TASK STATUS*
    ━━━━━━━━━━━━━━━━
    🌅 Opening: {op_done}/{op_tot}
    🌇 Closing: {cl_done}/{cl_tot}
    📱 Social: {soc_done}/{soc_tot}
    🤝 Interaction: {int_done}/{int_tot}
    
    *📝 DISCREPANCIES & NOTES*
    ━━━━━━━━━━━━━━━━
    {notes_section}
    
    📌 Shift Notes:
    {st.session_state.get('dn_notes', '-')}
    """
    
    # =====================================================
    # ARCHIVE + PDF SECTION
    # =====================================================
    
    crep1, crep2 = st.columns(2)
    
    with crep1:
    
        if st.button("💾 ARCHIVE SHIFT & DATA", use_container_width=True):
    
            printer_snapshot = {
                "start": st.session_state.get("printer_start"),
                "end": st.session_state.get("printer_end"),
                "difference": st.session_state.get("printer_diff")
            }
    
            db["history"].append({
                "date": str(date.today()),
                "branch": branch,
                "staff": st.session_state.get("user"),
                "sales": sys_sales,
                "diff": diff,
                "expenses": ex_val,
                "exp_note": f"{ex_cat}: {ex_note}",
                "printer_snapshot": printer_snapshot
            })
    
            save_db(db)
            st.success("✅ Shift Archived Successfully!")
        # =====================================================
        # PDF + WHATSAPP
        # =====================================================
    
    with crep1:
        if st.button("📄 GENERATE PRO PDF", use_container_width=True):
            pdf_bytes = create_downloadable_pdf(
                branch,
                st.session_state.get("user"),
                str(date.today()),
                sys_sales,
                ex_val,
                f"{ex_cat}: {ex_note}",
                diff,
                st.session_state.get("printer_diff", {}).get("Kyocera", {}),
                st.session_state.get("printer_diff", {}).get("Xerox", {}),
                st.session_state.get("ops", 0) - st.session_state.get("ope", 0),
                st.session_state.get("v22_val", 0)
            )
    
            st.download_button(
                "📥 Download PDF",
                pdf_bytes,
                file_name=f"NMS_{date.today()}.pdf",
                key="pdf_download"
            )
    with crep2:
        url = f"https://wa.me/{MANAGER_PHONE}?text={urllib.parse.quote(wa_text)}"
        st.markdown(
            f'<a href="{url}" target="_blank">'
            f'<button style="width:100%; background-color:#25D366; color:white; '
            f'border:none; padding:15px; border-radius:10px; cursor:pointer; '
            f'font-weight:bold; font-size:16px;">'
            f'📱 SEND TO WHATSAPP</button></a>',
            unsafe_allow_html=True
        )
