import streamlit as st
import pandas as pd
from datetime import datetime, date
import json
import os
import io
import base64
import urllib.parse
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter, landscape
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch

# --- 1. إعدادات قاعدة البيانات (Database Configuration) ---
from database import load_db, save_db, MANAGER_PHONE
db = load_db()

# --- 2. Advanced PDF Generation (تقرير شامل) ---
def create_downloadable_pdf(branch, staff_name, date_str, sales, expenses, exp_note, diff, kyo_data, xerox_data, opay_move, debit_v22):
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=landscape(letter), topMargin=30, bottomMargin=30)
    elements = []
    styles = getSampleStyleSheet()
    
    # تنسيقات مخصصة
    title_style = ParagraphStyle('Title', parent=styles['Heading1'], fontSize=24, alignment=1, spaceAfter=20, textColor=colors.darkblue)
    sub_style = ParagraphStyle('Sub', parent=styles['Normal'], fontSize=12, alignment=1, spaceAfter=30)
    
    # 1. الترويسة (لوجو + صورة الموظف)
    logo_img = None
    staff_img = None
    
    if db.get("logo"):
        try:
            logo_bytes = base64.b64decode(db["logo"])
            logo_img = Image(io.BytesIO(logo_bytes), width=1.5*inch, height=1.5*inch)
        except: pass

    staff_data = db["users"].get(st.session_state['user'], {})
    if staff_data.get("photo"):
        try:
            staff_bytes = base64.b64decode(staff_data["photo"])
            staff_img = Image(io.BytesIO(staff_bytes), width=1.2*inch, height=1.2*inch)
        except: pass

    header_data = [[logo_img if logo_img else "", Paragraph(f"<b>NMS ENTERPRISE REPORT</b><br/>{branch}", title_style), staff_img if staff_img else ""]]
    header_table = Table(header_data, colWidths=[2*inch, 6*inch, 2*inch])
    header_table.setStyle(TableStyle([('ALIGN', (0,0), (-1,-1), 'CENTER'), ('VALIGN', (0,0), (-1,-1), 'MIDDLE')]))
    elements.append(header_table)
    elements.append(Spacer(1, 10))
    elements.append(Paragraph(f"Date: {date_str} | Generated By: {staff_name}", sub_style))

    # 2. الجدول المالي
    elements.append(Paragraph("💰 Financial Summary", styles['Heading2']))
    fin_data = [
        ["Item", "Value", "Notes"],
        ["Total Sales", f"{sales:,.2f}", "-"],
        ["Expenses", f"{expenses:,.2f}", exp_note],
        ["Opay Movement", f"{opay_move:,.2f}", "-"],
        ["Debit", f"{debit_v22:,.2f}", "Postponed"],
        ["NET DIFFERENCE", f"{diff:,.2f}", "Final Status"]
    ]
    fin_table = Table(fin_data, colWidths=[2.5*inch, 2.5*inch, 4*inch])
    fin_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.darkblue),
        ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke),
        ('ALIGN', (0,0), (-1,-1), 'CENTER'),
        ('GRID', (0,0), (-1,-1), 1, colors.black),
        ('BACKGROUND', (0,5), (-1,5), colors.lightgrey),
        ('FONTNAME', (0,5), (-1,5), 'Helvetica-Bold'),
    ]))
    elements.append(fin_table)
    elements.append(Spacer(1, 20))

    # 3. جدول الطابعات
    elements.append(Paragraph("🖨️ Printers Analysis", styles['Heading2']))
    prn_data = [
        ["Machine", "Total Used", "Paper Jam", "1-Sided", "2-Sided"],
        ["Kyocera", kyo_data['used'], kyo_data['jam'], kyo_data['1s'], kyo_data['2s']],
        ["Xerox", xerox_data['used'], xerox_data['jam'], xerox_data['1s'], xerox_data['2s']]
    ]
    prn_table = Table(prn_data, colWidths=[2*inch, 1.5*inch, 1.5*inch, 2*inch, 2*inch])
    prn_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.darkred),
        ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke),
        ('ALIGN', (0,0), (-1,-1), 'CENTER'),
        ('GRID', (0,0), (-1,-1), 1, colors.black)
    ]))
    elements.append(prn_table)

    doc.build(elements)
    return buffer.getvalue()

# --- 3. Session Setup ---
st.set_page_config(page_title="NMS ERP Platinum", layout="wide", page_icon="🚀")

if 'logged_in' not in st.session_state:
    st.session_state.update({'logged_in': False, 'user': None, 'role': None})

def sync_draft():
    if st.session_state['logged_in']:
        user = st.session_state['user']
        draft_keys = ('s_','o_','e_','c_','m_','i_','ks','xs','op','u10','v22','ex','kj','xj','dn','k1','k2','x1','x2')
        draft_data = {k: v for k, v in st.session_state.items() if k.startswith(draft_keys)}
        if "drafts" not in db: db["drafts"] = {}
        db["drafts"][user] = draft_data
        save_db(db)

# --- 4. Login Screen ---
if not st.session_state['logged_in']:
    st.title("🔐 NMS Enterprise Access")
    c1, c2 = st.columns(2)
    with c1:
        if db.get("logo"): st.image(base64.b64decode(db["logo"]), width=350)
        else: st.info("ℹ️ Upload Company Logo in Admin Panel")
    with c2:
        st.write("### 🔑 Secure Login")
        u = st.selectbox("Select Your Account", list(db["users"].keys()))
        p = st.text_input("Enter Password", type="password")
        if st.button("🚀 Login", use_container_width=True):
            if u in db["users"] and "pass" in db["users"][u] and db["users"][u]["pass"] == p:
                st.session_state.update({'logged_in': True, 'user': u, 'role': db["users"][u]["role"]})
                if u in db.get("drafts", {}):
                    for key, val in db["drafts"][u].items(): st.session_state[key] = val
                db["logs"].append({"user": u, "time": datetime.now().strftime("%Y-%m-%d %H:%M:%S"), "action": "Login"})
                save_db(db); st.rerun()
            else: st.error("❌ Access Denied")

else:
    # --- 5. Sidebar System ---
    with st.sidebar:
        user_info = db["users"][st.session_state['user']]
        if user_info.get("photo"): 
            st.image(base64.b64decode(user_info["photo"]), width=120)
        else:
            st.write("👤 No Photo")
            
        st.header(f"Hi, {user_info['full_name']}")
        
        # --- بوابة الموظف (Self-Service) ---
        if st.session_state['role'] == 'user':
            st.divider()
            st.subheader("📂 My Financial Profile")
            st.write(f"**📅 Hiring Date:** {user_info.get('hiring_date', '-')}")
            st.metric("💰 Base Salary", f"{user_info.get('salary', 0):,.2f} LE")
            
            with st.expander("🎁 My Bonuses", expanded=False):
                if user_info['bonus']: st.dataframe(pd.DataFrame(user_info['bonus']))
                else: st.info("No bonuses yet.")
                    
            with st.expander("⏳ Overtime", expanded=False):
                if user_info['overtime']: st.dataframe(pd.DataFrame(user_info['overtime']))
                else: st.info("No overtime yet.")
                    
            with st.expander("⚠️ My Deductions", expanded=False):
                if user_info['deductions']: st.dataframe(pd.DataFrame(user_info['deductions']))
                else: st.success("Clean Record! No deductions.")
                    
            with st.expander("🏖️ Extra Leave", expanded=False):
                if user_info['extra_leaves']: st.dataframe(pd.DataFrame(user_info['extra_leaves']))
                else: st.success("Clean Record! No extra_leaves.")
                    
        if st.button("🚪 Logout", use_container_width=True):
            st.session_state['logged_in'] = False; st.rerun()
        
        # --- صلاحيات المدير المطلقة (Master Control) ---
        if st.session_state['role'] == 'admin':
            st.divider()
            st.subheader("⚙️ Admin Authority")
            admin_choice = st.selectbox("Select Management Module:", [
                "👥 Manage Employees (HR)", 
                "💰 Payroll & Money", 
                "📝 Tasks & Checklists", 
                "🏢 Branches & Expenses", 
                "📂 Archive & History",
                "🎓 Employee Training"
            ])            
            
            # 1. إدارة الموظفين (HR)
            if admin_choice == "👥 Manage Employees (HR)":
                st.info("Edit, Delete, or Add Employees")
                target = st.selectbox("Select Employee to Edit", list(db["users"].keys()))
                u_prof = db["users"][target]
                
                with st.expander("📸 Update Photo", expanded=False):
                    new_pic = st.file_uploader("Upload Photo", type=['png','jpg'])
                    if st.button("Save Photo"):
                        if new_pic:
                            db["users"][target]["photo"] = base64.b64encode(new_pic.getvalue()).decode()
                            save_db(db); st.success("Photo Updated!"); st.rerun()

                with st.expander("📝 Edit Personal Details", expanded=True):
                    up_full = st.text_input("Full Name", value=u_prof.get('full_name', ''))
                    up_pass = st.text_input("Password", value=u_prof.get('pass', ''))
                    up_phone = st.text_input("Phone Number", value=u_prof.get('phone', ''))
                    up_email = st.text_input("E-Mail", value=u_prof.get('email', ''))                    
                    up_nid = st.text_input("National ID", value=u_prof.get('national_id', ''))
                    up_addr = st.text_area("Address", value=u_prof.get('address', ''))
                    up_qual = st.text_input("Qualification", value=u_prof.get('qualification', ''))
                    if st.button("💾 Save Changes"):
                        db["users"][target].update({
                            "full_name": up_full, "pass": up_pass, "phone": up_phone,
                            "national_id": up_nid, "address": up_addr, "qualification": up_qual
                        })
                        save_db(db); st.success("Saved")
                
                # زر حذف الموظف
                if target != 'admin':
                    if st.button("🗑️ Delete This Employee", type="primary"):
                        del db["users"][target]
                        save_db(db); st.warning(f"User {target} Deleted!"); st.rerun()
                
                st.write("---")
                st.write("#### ➕ Add New Employee")
                new_u = st.text_input("New Username")
                if st.button("Create Account"):
                    if new_u and new_u not in db["users"]:
                        db["users"][new_u] = {
                            "pass": "123", "role": "user", "full_name": new_u,
                            "salary": 0.0, "bonus": [], "deductions": [], "overtime": [], "extra_leaves": [], "photo": None, "hiring_date": str(date.today()),
                            "phone": "", "national_id": "", "address": "", "qualification": ""
                        }
                        save_db(db); st.success("Created"); st.rerun()

            # 2. الرواتب والماليات
            elif admin_choice == "💰 Payroll & Money":
                st.info("Manage Salaries, Bonuses & Deductions")
                target = st.selectbox("Select Employee", list(db["users"].keys()))
                u_fin = db["users"][target]
                
                col_s1, col_s2 = st.columns(2)
                with col_s1: sal = st.number_input("Base Salary", value=float(u_fin.get('salary', 0)))
                with col_s2: hire = st.date_input("Hiring Date", value=datetime.strptime(u_fin.get('hiring_date', "2024-01-01"), "%Y-%m-%d"))
                if st.button("💾 Update Contract"):
                    db["users"][target]["salary"] = sal
                    db["users"][target]["hiring_date"] = str(hire)
                    save_db(db); st.success("Contract Updated")
                
                st.divider()
                st.write("**Add Financial Entry:**")
                dev_type = st.radio("Type", ["Bonus 🎁", "Deductions ⚠️", "Overtime ⏳", "Extra Leave 🏖️"], horizontal=True)
                amt = st.number_input("Value (LE)", step=10.0)
                note = st.text_input("Reason / Note")
                if st.button("✅ Submit Entry"):
                    key = dev_type.split()[0].lower()
                    if key == "extra": key = "extra_leaves"
                    db["users"][target][key].append({"date": str(date.today()), "val": amt, "note": note})
                    save_db(db); st.success("Added to HR Record")

            # 3. إدارة المهام
            elif admin_choice == "📝 Tasks & Checklists":
                cat = st.selectbox("Category", ["opening", "closing", "social", "interaction"])
                for i, t in enumerate(db["tasks"][cat]):
                    c1, c2 = st.columns([5, 1])
                    c1.text(f"📌 {t}")
                    if c2.button("🗑️", key=f"del_t_{cat}_{i}"):
                        db["tasks"][cat].pop(i); save_db(db); st.rerun()
                new_t = st.text_input("New Task")
                if st.button("➕ Add Task"):
                    if new_t: db["tasks"][cat].append(new_t); save_db(db); st.rerun()
                        
            # 4. الفروع والمصاريف
            elif admin_choice == "🏢 Branches & Expenses":
                st.info("Manage Locations & Expenses")
                
                st.write("**🏢 Branches (الفروع)**")
                br_sel = st.selectbox("Select Branch", db["branches"])
                c_br1, c_br2 = st.columns(2)
                with c_br1:
                    new_br_name = st.text_input("Rename Branch", value=br_sel)
                    if st.button("✏️ Rename"):
                        idx = db["branches"].index(br_sel)
                        db["branches"][idx] = new_br_name
                        save_db(db); st.success("Renamed!"); st.rerun()
                with c_br2:
                    if st.button("🗑️ Delete Branch", type="primary"):
                        db["branches"].remove(br_sel)
                        save_db(db); st.warning("Deleted!"); st.rerun()
                
                new_b_add = st.text_input("New Branch Name")
                if st.button("➕ Create Branch"):
                    if new_b_add: db["branches"].append(new_b_add); save_db(db); st.rerun()

                st.divider()
                st.write("**💸 Expense Categories (بنود المصاريف)**")
                for i, e in enumerate(db["expense_categories"]):
                    ce1, ce2 = st.columns([5,1]); ce1.text(f"🔹 {e}")
                    if ce2.button("✖️", key=f"del_ex_{i}"): db["expense_categories"].pop(i); save_db(db); st.rerun()
                new_ex = st.text_input("New Expense Category")
                if st.button("➕ Add Expense Category"):
                    if new_ex: db["expense_categories"].append(new_ex); save_db(db); st.rerun()

            elif admin_choice == "📂 Archive & History":
                st.header("📂 Archive & History")
                
                # التأكد من صلاحية الأدمن (حسب نظامك)
                if st.session_state.get('role') != 'admin':
                    st.error("Access Denied: Admins Only.")
                    pass
            
                st.divider()
                
                # التحقق من وجود بيانات في الهيستوري
                if not db.get("history") or len(db["history"]) == 0:
                    st.info("No archived shifts found yet.")
                else:
                    # 1. Dashboard Metrics (إحصائيات سريعة)
                    h_data = db["history"]
                    
                    # استخدام try-except أو التحويل الآمن لضمان عدم حدوث خطأ لو القيمة نصية
                    try:
                        total_sales = sum(float(item.get('sales', 0)) for item in h_data)
                        total_exp = sum(float(item.get('expenses', 0)) for item in h_data)
                        total_diff = sum(float(item.get('diff', 0)) for item in h_data)
                    except ValueError:
                        st.error("Error in data types within History. Please check database.")
                        total_sales = total_exp = total_diff = 0
            
                    m1, m2, m3 = st.columns(3)
                    m1.metric("Total Sales", f"{total_sales:,.2f} LE")
                    m2.metric("Total Expenses", f"{total_exp:,.2f} LE")
                    m3.metric("Net Cash Diff", f"{total_diff:,.2f} LE", delta=total_diff, delta_color="normal")
            
                    st.divider()
            
                    # 2. Detailed Data Table (عرض الجدول)
                    st.subheader("📜 Detailed Shift History")
                    
                    # تحويل البيانات لـ DataFrame لسهولة العرض
                    df_history = pd.DataFrame(reversed(h_data))
                    
                    # خريطة تسمية الأعمدة لتناسب الكود الخاص بك
                    column_mapping = {
                        "date": "Date",
                        "staff": "Employee",
                        "branch": "Branch",
                        "sales": "Sales",
                        "expenses": "Expenses",
                        "exp_note": "Exp. Details",
                        "diff": "Cash Diff",
                        "kyo_jam": "Kyo Jam",
                        "xerox_jam": "Xerox Jam"
                    }
                    
                    # فلترة الأعمدة الموجودة فعلياً في الـ DataFrame فقط لتجنب الأخطاء
                    existing_columns = {k: v for k, v in column_mapping.items() if k in df_history.columns}
                    
                    st.dataframe(
                        df_history.rename(columns=existing_columns),
                        use_container_width=True,
                        column_config={
                            "Sales": st.column_config.NumberColumn(format="%.2f LE"),
                            "Expenses": st.column_config.NumberColumn(format="%.2f LE"),
                            "Cash Diff": st.column_config.NumberColumn(format="%.2f LE"),
                        }
                    )
            
                    # 3. Quick Actions (عمليات الحذف والتأمين)
                    st.divider()
                    with st.expander("🗑️ Advanced Settings (Danger Zone)"):
                        st.warning("Action below is irreversible!")
                        confirm_check = st.checkbox("I understand that 'Clear History' will delete everything.")
                        if confirm_check:
                            if st.button("🚨 Permanently Clear All History"):
                                db["history"] = []
                                save_db(db)
                                st.success("History Cleared!")
                                st.rerun()  
                                
            elif admin_choice == "🎓 Employee Training":
                    """
                    دالة عرض مركز التدريب والتأهيل الاحترافي لمركز NMS Enterprise
                    مصممة لتكون تفاعلية وشاملة لكل جوانب العمل.
                    """
                    st.markdown("""
                        <style>
                        .main-title { font-size: 40px; font-weight: bold; color: #1E3A8A; text-align: center; margin-bottom: 20px; }
                        .section-header { background-color: #F1F5F9; padding: 10px; border-radius: 5px; border-left: 5px solid #1E3A8A; margin-top: 20px; }
                        .card { background-color: white; padding: 20px; border-radius: 10px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); margin-bottom: 15px; }
                        </style>
                    """, unsafe_allow_html=True)
                
                    st.markdown('<div class="main-title">🎓 الأكاديمية التدريبية لـ NMS Enterprise</div>', unsafe_allow_html=True)
                    
                    # تبويبات التدريب
                    tabs = st.tabs(["📋 ميثاق العمل", "⚙️ الدليل الفني", "🤝 خدمة العملاء", "💻 التحول الرقمي"])
                
                    # 1. ميثاق العمل (السياسات والالتزام)
                    with tabs[0]:
                        st.markdown('<div class="section-header">⚖️ القواعد الذهبية للالتزام</div>', unsafe_allow_html=True)
                        col1, col2 = st.columns(2)
                        with col1:
                            st.markdown("""
                            ### 🕒 الحضور والانصراف
                            - **التبكير:** الحضور قبل الشفت بـ 15 دقيقة لتسليم وتسلم العهدة.
                            - **البصمة:** تسجيل الحضور والانصراف فوراً (Fingerprint).
                            - **الزي:** الالتزام بقميص المركز النظيف والـ ID.
                            """)
                        with col2:
                            st.markdown("""
                            ### 💰 الأمانة المالية
                            - **الفاتورة:** لا يخرج ورق مطبوع بدون تسجيله على السيستم.
                            - **العربون:** قاعدة ثابتة (لا عمل بدون دفع مسبق أو عربون 50%).
                            - **العهدة:** الموظف مسؤول عن أي عجز في درج الكاش خلال شفته.
                            """)
                
                    # 2. الدليل الفني (التعامل مع المعدات)
                    with tabs[1]:
                        st.markdown('<div class="section-header">🛠️ تشغيل وصيانة المعدات</div>', unsafe_allow_html=True)
                        with st.expander("🖨️ ماكينات التصوير (Xerox & Kyocera)"):
                            st.write("""
                            1. **التشغيل الصحيح:** التأكد من استقرار الجهد الكهربائي قبل التشغيل.
                            2. **حشر الورق:** التعامل بهدوء مع الحشر، سحب الورقة في اتجاه خروجها وليس العكس.
                            3. **الألوان:** مراجعة جودة الألوان كل 100 نسخة لضمان عدم وجود بهتان.
                            """)
                        with st.expander("✂️ أدوات التجهيز (Finishers)"):
                            st.write("""
                            - **التغليف الحراري:** انتظر وصول الماكينة للدرجة المطلوبة (اللمبة الخضراء).
                            - **المقص الكهربائي:** الالتزام التام بقواعد السلامة، يمنع وضع اليد قريباً من السكينة.
                            - **التكعيب:** تأكد من عدد الورق المناسب لحجم السلك (الحلزوني).
                            """)
                
                    # 3. خدمة العملاء (الجانب السلوكي)
                    with tabs[2]:
                        st.markdown('<div class="section-header">🌟 فن التعامل مع الجمهور</div>', unsafe_allow_html=True)
                        st.success("العميل ليس دائماً على حق، لكنه دائماً عميلنا ويجب احترامه.")
                        st.info("""
                        - **الاستقبال:** ابتسامة وكلمة ترحيب "أهلاً بك في NMS، كيف نساعدك؟".
                        - **الاعتراض:** عند وجود شكوى، استمع كاملاً دون مقاطعة، ثم قدم حلاً.
                        - **التسليم:** تأكد من أن العميل راجع شغله (العدد والجودة) قبل مغادرة المركز.
                        """)
                
                    # 4. التحول الرقمي (البرامج والذكاء الاصطناعي)
                    with tabs[3]:
                        st.markdown('<div class="section-header">🚀 أدوات العصر الحديث</div>', unsafe_allow_html=True)
                        c1, c2, c3 = st.columns(3)
                        with c1:
                            st.image("https://img.icons8.com/color/96/canva.png", width=60)
                            st.markdown("**Canva**\n\nللتصميمات السريعة والسوشيال ميديا.")
                        with c2:
                            st.image("https://img.icons8.com/color/96/chatgpt.png", width=60)
                            st.markdown("**AI Tools**\n\nاستخدام الذكاء الاصطناعي لتحسين النصوص.")
                        with c3:
                            st.image("https://img.icons8.com/color/96/microsoft-excel-2019.png", width=60)
                            st.markdown("**Office**\n\nاحتراف التنسيق والطباعة من Word و Excel.")
                
                    st.divider()
                    
                    # جزء تفاعلي لإقرار الموظف
                    st.markdown("### 📝 إقرار إتمام التدريب")
                    agree = st.checkbox("أقر أنا الموظف المسجل دخوله حالياً، أنني قرأت كافة التعليمات أعلاه وألتزم بتطبيقها حرفياً.")
                    if st.button("اعتماد إتمام التدريب"):
                        if agree:
                            st.balloons()
                            st.success(f"تم تسجيل اعتمادك للدليل التدريبي يا {st.session_state.get('user', 'موظفنا العزيز')}.")
                            # هنا يمكنك إضافة كود لحفظ هذا الاعتماد في قاعدة البيانات إذا أردت
                        else:
                            st.warning("يرجى التأشير على الإقرار أولاً.")
                
                # لاستدعاء الدالة في القائمة الجانبية أو كصفحة مستقلة:
                # if st.session_state['page'] == 'training':
                #     show_training_page()
    
    with st.expander("🧰 Backup Manager"):
        backup_folder = "backups"
        if not os.path.exists(backup_folder) or len(os.listdir(backup_folder)) == 0:
            st.warning("لا توجد نسخ احتياطية حتى الآن.")
        else:
            # ترتيب الملفات حسب التاريخ الأحدث
            backup_files = sorted(os.listdir(backup_folder), reverse=True)
            latest_file = backup_files[0]
            latest_path = os.path.join(backup_folder, latest_file)
    
            st.info(f"🕒 أحدث نسخة: {latest_file}")
    
            with open(latest_path, "rb") as f:
                st.download_button("📥 تحميل النسخة الاحتياطية", f, file_name=latest_file)
                st.divider()
    st.markdown("### ♻️ استرجاع نسخة قديمة")

    if not os.path.exists(backup_folder):
        os.makedirs(backup_folder)

    restore_file = st.selectbox("اختر نسخة احتياطية", os.listdir(backup_folder))
    if st.button("♻️ استرجاع النسخة المحددة"):
        selected_path = os.path.join(backup_folder, restore_file)
        with open(selected_path, "r", encoding="utf-8") as f:
            restored_data = json.load(f)
        save_db(restored_data)
        st.success("✅ تم استرجاع النسخة بنجاح. برجاء إعادة تحميل الصفحة.")
    # --- 6. Main Dashboard: DAILY OPERATIONS ---
    st.title("📊 NMS ERP - Daily Operations")
    m1, m2, m3, m4 = st.columns(4)
    with m1: branch = st.selectbox("📍 Branch", db["branches"])
    with m2: shift = st.selectbox("🕒 Shift", ["Morning", "Between", "Night"])
    with m3: st.info(f"📅 {datetime.now().strftime('%Y-%m-%d')}")
    with m4: st.info(f"👤 {st.session_state['user']}")

    tab1, tab2, tab3 = st.tabs(["🟢 OPENING", "🔴 CLOSING", "📱 SOCIAL"])

    # --- TAB 1: OPENING ---
    with tab1:
        st.subheader("🌅 Opening Procedures")
        c_o1, c_o2, c_o3 = st.columns([1, 1.5, 1.5])
        with c_o1:
            st.markdown("#### ✅ Opening Tasks")
            for t in db["tasks"]["opening"]: st.checkbox(t, key=f"s_{t}", on_change=sync_draft)
        with c_o2:
            st.markdown("#### 💵 Cash Denominations (Opening)")
            t_open = 0.0
            for d in [200, 100, 50, 20, 10, 5]:
                v = st.number_input(f"{d} LE", min_value=0, step=1, key=f"o_{d}", on_change=sync_draft)
                t_open += (v * d)
            o_coins = st.number_input("Coins", step=0.5, key="o_coins", on_change=sync_draft)
            t_open += o_coins
            st.success(f"**Total Opening: {t_open:,.2f} LE**")
        with c_o3:
            st.markdown("#### 🔢 Initial Counters")
            ks = st.number_input("Kyocera Start", step=1, key="ks", on_change=sync_draft)
            xs = st.number_input("Xerox Start", step=1, key="xs", on_change=sync_draft)
            ops = st.number_input("Opay Start Balance", step=0.01, key="ops", on_change=sync_draft)
            u10 = st.number_input("Debit", step=1.0, key="u10_val", on_change=sync_draft)

    # --- TAB 2: CLOSING ---
    with tab2:
        st.subheader("🌇 Closing Procedures")
        c_c1, c_c2, c_c3 = st.columns([1, 1.5, 1.5])
        with c_c1:
            st.markdown("#### ✅ Closing Tasks")
            for t in db["tasks"]["closing"]: st.checkbox(t, key=f"e_{t}", on_change=sync_draft)
            st.divider()
            st.markdown("#### 💳 System & Payments")
            sys_sales = st.number_input("💻 System Sales", step=1.0, key="c_sys_sales", on_change=sync_draft)
            insta = st.number_input("📱 Instapay", step=1.0, key="c_insta", on_change=sync_draft)
            wall = st.number_input("👛 Wallet (VF/Etisalat)", step=1.0, key="c_wall", on_change=sync_draft)
            visa = st.number_input("💳 Visa", step=1.0, key="c_visa", on_change=sync_draft)
            v22 = st.number_input("📉 Debit", step=1.0, key="v22_val", on_change=sync_draft)
            t_digital = insta + wall + visa
        with c_c2:
            st.markdown("#### 💵 Cash Denominations (Closing)")
            t_close = 0.0
            for d in [200, 100, 50, 20, 10, 5]:
                v = st.number_input(f"{d} LE ", min_value=0, step=1, key=f"c_{d}", on_change=sync_draft)
                t_close += (v * d)
            c_coins = st.number_input("Closing Coins ", step=0.5, key="c_coins", on_change=sync_draft)
            t_close += c_coins
            
            st.divider()
            st.markdown("#### 💸 Expenses Detail")
            ex_cat = st.selectbox("Category", db["expense_categories"], key="ex_cat")
            ex_val = st.number_input("Amount", step=1.0, key="ex_val")
            ex_note = st.text_input("Details / Reason", key="ex_note")
            
            # CORE MATH
            expected = t_open + sys_sales + u10 - ex_val - v22 - t_digital
            diff = t_close - expected
            st.metric("Expected Drawer", f"{expected:,.2f} LE")
            if abs(diff) < 0.1: st.success("✨ Perfect Match!")
            elif diff > 0: st.warning(f"➕ Surplus: {diff:,.2f}")
            else: st.error(f"➖ Shortage: {diff:,.2f}")

        with c_c3:
            st.markdown("#### 🖨️ Printers Detail")
            st.info("Kyocera")
            ke = st.number_input("Kyo End", step=1, key="ke")
            k1s = st.number_input("1-Sided", step=1, key="k1s_v")
            k2s = st.number_input("2-Sided", step=1, key="k2s_v")
            kj = st.number_input("⚠️ Paper Jam", step=1, key="kj_v", on_change=sync_draft)
            
            st.info("Xerox")
            xe = st.number_input("Xerox End", step=1, key="xe")
            x1s = st.number_input("1-Sided", step=1, key="x1s_v")
            x2s = st.number_input("2-Sided", step=1, key="x2s_v")
            xj = st.number_input("⚠️ Paper Jam", step=1, key="xj_v", on_change=sync_draft)
            
            st.divider()
            ope = st.number_input("Opay End Balance", step=0.01, key="ope")
            st.write(f"📉 Opay Used: {ops - ope:,.2f}")
            
            st.text_area("📝 Draft Notes / Handover", key="dn_notes", on_change=sync_draft)

    # --- TAB 3: SOCIAL ---
    with tab3:
        st.subheader("📱 Marketing & Finalization")
        sc1, sc2 = st.columns(2)
        with sc1:
            st.markdown("#### 📢 Social Media Tasks")
            for t in db["tasks"]["social"]: st.checkbox(t, key=f"m_{t}", on_change=sync_draft)
        with sc2:
            st.markdown("#### ❤️ Interaction Tasks")
            for t in db["tasks"]["interaction"]: st.checkbox(t, key=f"i_{t}", on_change=sync_draft)
        
        st.divider()
        st.write("### 🏁 End Shift Actions")
        
# --- WhatsApp Construction ---
        
        # 1. Calculate Task Statistics (Safe access via session_state)
        def count_tasks(prefix):
            all_keys = db["tasks"].get(prefix, [])
            done = 0
            # Mapping internal prefixes to session state keys
            map_p = {'opening':'s_', 'closing':'e_', 'social':'m_', 'interaction':'i_'}
            p = map_p.get(prefix, '')
            for t in all_keys:
                if st.session_state.get(f"{p}{t}"):
                    done += 1
            return done, len(all_keys)

        op_done, op_tot = count_tasks('opening')
        cl_done, cl_tot = count_tasks('closing')
        soc_done, soc_tot = count_tasks('social')
        int_done, int_tot = count_tasks('interaction')

        # 2. Identify Discrepancies (Financial & Printers)
        error_notes = []
        if abs(diff) > 0.1:
            error_notes.append(f"⚠️ Cash Diff: {diff:,.2f}")
        
        # Safe retrieval of printer data
        _ks = st.session_state.get('ks', 0)
        _ke = st.session_state.get('ke', 0)
        _xs = st.session_state.get('xs', 0)
        _xe = st.session_state.get('xe', 0)
        _k1s = st.session_state.get('k1s_v', 0)
        _k2s = st.session_state.get('k2s_v', 0)
        _x1s = st.session_state.get('x1s_v', 0)
        _x2s = st.session_state.get('x2s_v', 0)

        kyo_actual = _ke - _ks
        kyo_reported = _k1s + _k2s
        if kyo_actual != kyo_reported:
            error_notes.append(f"⚠️ Kyo Counter Diff: Actual {kyo_actual} vs Reported {kyo_reported}")
            
        xerox_actual = _xe - _xs
        xerox_reported = _x1s + _x2s
        if xerox_actual != xerox_reported:
            error_notes.append(f"⚠️ Xerox Counter Diff: Actual {xerox_actual} vs Reported {xerox_reported}")

        notes_section = "\n".join(error_notes) if error_notes else "✅ No discrepancies found"

        # 3. Build WhatsApp Message Body
        wa_text = f"*🚀 NMS ERP - SHIFT REPORT*\n" \
                  f"━━━━━━━━━━━━━━━━\n" \
                  f"📅 Date: {date.today()}\n" \
                  f"👤 Staff: {st.session_state['user']}\n" \
                  f"📍 Branch: {branch}\n" \
                  f"🕒 Shift: {shift}\n\n" \
                  f"*💰 FINANCIAL SUMMARY*\n" \
                  f"━━━━━━━━━━━━━━━━\n" \
                  f"💵 Opening Cash: {t_open:,.2f}\n" \
                  f"💻 System Sales: {sys_sales:,.2f}\n" \
                  f"💸 Expenses: {ex_val:,.2f} ({ex_cat}: {ex_note})\n" \
                  f"💳 Online/Digital: {t_digital:,.2f}\n" \
                  f"   (Wallet: {st.session_state.get('c_wall', 0)} | Insta: {st.session_state.get('c_insta', 0)} | Visa: {st.session_state.get('c_visa', 0)})\n" \
                  f"📉 Debit: {st.session_state.get('v22_val', 0):,.2f}\n" \
                  f"💰 Closing Drawer: {t_close:,.2f}\n" \
                  f"⚖️ Net Difference: {diff:,.2f}\n\n" \
                  f"*🖨️ PRINTER ANALYSIS*\n" \
                  f"━━━━━━━━━━━━━━━━\n" \
                  f"📠 Kyocera: {kyo_actual} (Jams: {st.session_state.get('kj_v', 0)})\n" \
                  f"📠 Xerox: {xerox_actual} (Jams: {st.session_state.get('xj_v', 0)})\n" \
                  f"📱 Opay Diff: {st.session_state.get('ops', 0) - st.session_state.get('ope', 0):,.2f}\n\n" \
                  f"*✅ TASK STATISTICS*\n" \
                  f"━━━━━━━━━━━━━━━━\n" \
                  f"🌅 Opening: {op_done}/{op_tot}\n" \
                  f"🌇 Closing: {cl_done}/{cl_tot}\n" \
                  f"📱 Social Media: {soc_done}/{soc_tot}\n" \
                  f"🤝 Interaction: {int_done}/{int_tot}\n\n" \
                  f"*📝 DISCREPANCIES & NOTES*\n" \
                  f"━━━━━━━━━━━━━━━━\n" \
                  f"{notes_section}\n" \
                  f"📌 Shift Notes: {st.session_state.get('dn_notes', '-')}"

        # --- Footer Action Buttons ---
        if st.button("💾 ARCHIVE SHIFT & DATA", use_container_width=True):
            db["history"].append({
                "date": str(date.today()), 
                "branch": branch, 
                "staff": st.session_state['user'],
                "sales": sys_sales, 
                "diff": diff, 
                "kyo_jam": st.session_state.get('kj_v', 0), 
                "xerox_jam": st.session_state.get('xj_v', 0), 
                "expenses": ex_val,
                "exp_note": f"{ex_cat}: {ex_note}"
            })
            if st.session_state['user'] in db["drafts"]: 
                del db["drafts"][st.session_state['user']]
            save_db(db)
            st.success("Shift Archived Successfully!")

        crep1, crep2 = st.columns(2)
        with crep1:
            if st.button("📄 GENERATE PRO PDF", use_container_width=True):
                kyo_d = {'used': _ke-_ks, 'jam': st.session_state.get('kj_v', 0), '1s': _k1s, '2s': _k2s}
                xerox_d = {'used': _xe-_xs, 'jam': st.session_state.get('xj_v', 0), '1s': _x1s, '2s': _x2s}
                pdf_bytes = create_downloadable_pdf(branch, st.session_state['user'], str(date.today()), sys_sales, ex_val, f"{ex_cat}: {ex_note}", diff, kyo_d, xerox_d, st.session_state.get('ops',0)-st.session_state.get('ope',0), st.session_state.get('v22_val',0))
                st.download_button("📥 Download Official Report", pdf_bytes, f"NMS_Pro_{date.today()}.pdf")
        with crep2:
            url = f"https://wa.me/{MANAGER_PHONE}?text={urllib.parse.quote(wa_text)}"
            st.markdown(f'<a href="{url}" target="_blank"><button style="width:100%; background-color:#25D366; color:white; border:none; padding:15px; border-radius:10px; cursor:pointer; font-weight:bold; font-size:16px;">📱 SEND TO WHATSAPP</button></a>', unsafe_allow_html=True)
