# pdf_service.py
import io
import base64
from datetime import date
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter, landscape
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image, PageBreak, KeepTogether
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from database_service import load_db

db = load_db()

def create_downloadable_pdf(
    branch,
    staff_name,
    date_str,
    sales,
    expenses,
    exp_note,
    diff,
    printer_diff,
    opay_move,
    debit_v22
):
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=landscape(letter), topMargin=24, bottomMargin=24)
    elements = []
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("Title", parent=styles["Heading1"], fontSize=20, alignment=1)
    sub_style = ParagraphStyle("Sub", parent=styles["Normal"], fontSize=10, alignment=1)

    # header: logo + title + staff photo
    logo = ""
    staff_img = ""
    if db.get("logo"):
        try:
            logo = Image(io.BytesIO(base64.b64decode(db["logo"])), width=1.2*inch, height=1.2*inch)
        except:
            logo = ""
    staff = db.get("users", {}).get(staff_name, {}) if staff_name else {}
    if staff and staff.get("photo"):
        try:
            staff_img = Image(io.BytesIO(base64.b64decode(staff["photo"])), width=1.0*inch, height=1.0*inch)
        except:
            staff_img = ""

    header = Table([[logo, Paragraph(f"<b>NMS SHIFT REPORT</b><br/>{branch}", title_style), staff_img]],
                   colWidths=[1.5*inch, 7.5*inch, 1.5*inch])
    header.setStyle(TableStyle([("ALIGN",(0,0),(-1,-1),"CENTER"), ("VALIGN",(0,0),(-1,-1),"MIDDLE")]))
    elements.append(header)
    elements.append(Spacer(1,8))
    elements.append(Paragraph(f"Date: {date_str} | By: {staff_name}", sub_style))
    elements.append(PageBreak())

    # Financial summary
    elements.append(Paragraph("Financial Summary", styles["Heading2"]))
    safe_note = Paragraph(str(exp_note) if exp_note else "-", styles["Normal"])
    fin_rows = [
        ["Item", "Value", "Notes"],
        ["Total Sales", f"{sales:,.2f}", "-"],
        ["Expenses", f"{expenses:,.2f}", safe_note],
        ["Opay Movement", f"{opay_move:,.2f}", "-"],
        ["Debit", f"{debit_v22:,.2f}", "-"],
        ["NET Difference", f"{diff:,.2f}", "Final"]
    ]
    fin_table = Table(fin_rows, colWidths=[3*inch, 3*inch, 5*inch], repeatRows=1)
    fin_table.setStyle(TableStyle([
        ("GRID",(0,0),(-1,-1),0.5,colors.grey),
        ("BACKGROUND",(0,0),(-1,0),colors.HexColor("#0f172a")),
        ("TEXTCOLOR",(0,0),(-1,0),colors.whitesmoke),
        ("ALIGN",(0,0),(-1,-1),"CENTER")
    ]))
    elements.append(KeepTogether([fin_table]))
    elements.append(PageBreak())

    # Printers table (dynamic)
    elements.append(Paragraph("Printers Analysis", styles["Heading2"]))
    prn_header = [["Printer","Used","Jam","1-Side","2-Side"]]
    prn_rows = prn_header[:]
    for name, v in (printer_diff or {}).items():
        prn_rows.append([name, v.get("used",0), v.get("jam",0), v.get("1s",0), v.get("2s",0)])
    prn_table = Table(prn_rows, colWidths=[3*inch, 1.5*inch, 1.5*inch, 1.5*inch, 1.5*inch], repeatRows=1)
    prn_table.setStyle(TableStyle([
        ("GRID",(0,0),(-1,-1),0.5,colors.grey),
        ("BACKGROUND",(0,0),(-1,0),colors.HexColor("#7f1d1d")),
        ("TEXTCOLOR",(0,0),(-1,0),colors.whitesmoke),
        ("ALIGN",(0,0),(-1,-1),"CENTER")
    ]))
    elements.append(KeepTogether([prn_table]))
    elements.append(Spacer(1,12))

    # footer summary
    elements.append(Paragraph(f"Generated by NMS System", styles["Normal"]))
    try:
        doc.build(elements)
    except Exception as e:
        # return a readable error inside PDF bytes? Here we raise to caller
        raise
    return buffer.getvalue()
