import io
import base64
from datetime import date
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter, landscape
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
import streamlit as st
from database import load_db  # تأكد إن الملف اسمه database.py

db = load_db()

def create_downloadable_pdf(branch, staff_name, date_str, sales, expenses, exp_note, diff, kyo_data, xerox_data, opay_move, debit_v22):
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=landscape(letter), topMargin=30, bottomMargin=30)
    elements = []
    styles = getSampleStyleSheet()

    # تنسيقات مخصصة
    title_style = ParagraphStyle('Title', parent=styles['Heading1'], fontSize=24, alignment=1, spaceAfter=20, textColor=colors.darkblue)
    sub_style = ParagraphStyle('Sub', parent=styles['Normal'], fontSize=12, alignment=1, spaceAfter=30)

    # 1. الترويسة (لوجو + صورة الموظف)
    logo_img = None
    staff_img = None

    if db.get("logo"):
        try:
            logo_bytes = base64.b64decode(db["logo"])
            logo_img = Image(io.BytesIO(logo_bytes), width=1.5*inch, height=1.5*inch)
        except:
            pass

    staff_data = db["users"].get(st.session_state['user'], {})
    if staff_data.get("photo"):
        try:
            staff_bytes = base64.b64decode(staff_data["photo"])
            staff_img = Image(io.BytesIO(staff_bytes), width=1.2*inch, height=1.2*inch)
        except:
            pass

    header_data = [[logo_img if logo_img else "", Paragraph(f"<b>NMS ENTERPRISE REPORT</b><br/>{branch}", title_style), staff_img if staff_img else ""]]
    header_table = Table(header_data, colWidths=[2*inch, 6*inch, 2*inch])
    header_table.setStyle(TableStyle([
        ('ALIGN', (0,0), (-1,-1), 'CENTER'),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE')
    ]))
    elements.append(header_table)
    elements.append(Spacer(1, 10))
    elements.append(Paragraph(f"Date: {date_str} | Generated By: {staff_name}", sub_style))

    # 2. الجدول المالي
    elements.append(Paragraph("💰 Financial Summary", styles['Heading2']))
    fin_data = [
        ["Item", "Value", "Notes"],
        ["Total Sales", f"{sales:,.2f}", "-"],
        ["Expenses", f"{expenses:,.2f}", exp_note],
        ["Opay Movement", f"{opay_move:,.2f}", "-"],
        ["Debit", f"{debit_v22:,.2f}", "Postponed"],
        ["NET DIFFERENCE", f"{diff:,.2f}", "Final Status"]
    ]
    fin_table = Table(fin_data, colWidths=[2.5*inch, 2.5*inch, 4*inch])
    fin_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.darkblue),
        ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke),
        ('ALIGN', (0,0), (-1,-1), 'CENTER'),
        ('GRID', (0,0), (-1,-1), 1, colors.black),
        ('BACKGROUND', (0,5), (-1,5), colors.lightgrey),
        ('FONTNAME', (0,5), (-1,5), 'Helvetica-Bold'),
    ]))
    elements.append(fin_table)
    elements.append(Spacer(1, 20))

    # 3. جدول الطابعات
    elements.append(Paragraph("🖨️ Printers Analysis", styles['Heading2']))
    prn_data = [
        ["Machine", "Total Used", "Paper Jam", "1-Sided", "2-Sided"],
        ["Kyocera", kyo_data['used'], kyo_data['jam'], kyo_data['1s'], kyo_data['2s']],
        ["Xerox", xerox_data['used'], xerox_data['jam'], xerox_data['1s'], xerox_data['2s']]
    ]
    prn_table = Table(prn_data, colWidths=[2*inch, 1.5*inch, 1.5*inch, 2*inch, 2*inch])
    prn_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.darkred),
        ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke),
        ('ALIGN', (0,0), (-1,-1), 'CENTER'),
        ('GRID', (0,0), (-1,-1), 1, colors.black)
    ]))
    elements.append(prn_table)

    doc.build(elements)
    return buffer.getvalue()
